<<<<<<< HEAD
---
- hosts: localhost
  connection: local
  gather_facts: False
#  include_vars: setupvariables.yml
  tasks:
    - name: Provision a set of instances
      ec2:
         aws_access_key:
         aws_secret_key:
         key_name: AcademyKeyPair
         group: team2DEV
         instance_type: t2.micro
         image: ami-f1d7c395
         wait: true
         exact_count: 1
         region: eu-west-2
         count_tag:
            Name: Team2
         instance_tags:
            Name: Team2
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: configuration play
  hosts: ec2hosts
# user: ubuntu
  gather_facts: true
  tasks:
    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes
      with_items:
        - git
        - docker.io

- name: Build an image by running ansible in a container
  hosts: all
  become: yes
  tasks:
  - name: Start a container
    docker_container:
      name: jenkins
      image: jenkins:latest
      command: "sleep infinity"
=======
---
- hosts: localhost
  connection: local
  gather_facts: False
  include_vars: setupvariables.yml
  tasks:
    - name: Provision a set of instances
      ec2:
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         key_name: General
         group: default
         instance_type: t2.micro
         image: ami-f1d7c395
         wait: true
         exact_count: 1
         region: eu-west-2
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"


    - hosts: ec2hosts
      name: configuration play
      user: ubuntu
      gather_facts: true
      tasks:
        - name: install base packages
          apt: pkg={{item}} state=present update_cache=yes
          with_items:
            - git
            - docker.io

    #- name: Build an image by running ansible in a container
    #  hosts: all
    #  become: yes
    #  tasks:
    #   - name: Start a container
    #     docker_container:
    #       name: jenkins
    #       image: jenkins:latest
    #       command: "sleep infinity"
>>>>>>> a3bc20660623f604e338caa42080c662cb28807e
