---

- hosts: localhost
  connection: local
  gather_facts: False
#  include_vars: setupvariables.yml
  tasks:
    - name: Provision a set of instances
      ec2:
         aws_access_key: 
         aws_secret_key: 
         key_name: Team2KP
         vpc_subnet_id: subnet-7d578c06
         group: team2DEV
         instance_type: t2.small
         image: ami-f1d7c395
         wait: true
         exact_count: 1
         region: eu-west-2
         user_data: "{{ lookup('file', 'remove.sh') }}"
         count_tag:
            Name: Team2Agent1-Jenkins/Jira/Tomcat
         instance_tags:
            Name: Team2Agent1-Jenkins/Jira/Tomcat
      register: ec2

    - name: Add all instance public IPs to host group
      become: yes
      add_host: hostname={{ item.public_ip }} groups=ec2hosts1
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      become: yes
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 20
        timeout: 500
        state: started
      with_items: "{{ ec2.instances }}"


- name: dependency provisioning
  hosts: ec2hosts1
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: install python2
      raw: sudo apt-get -y install python-simplejson


- name: configuration play
  hosts: ec2hosts1
  become: yes
  user: ubuntu
  gather_facts: true
  pre_tasks: 
   - name: Refresh apt cache
     become: no
     local_action: shell ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ inventory_hostname }} sudo apt-get update
       
   - name: Install Python-apt to pull in Python
     become: no
     local_action: shell ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ inventory_hostname }} sudo apt-get install --no-install-recommends --assume-yes python-apt
  tasks:
    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes
      with_items:
        - git
        - python-pip
        - docker.io


- name: Install Docker
  hosts: ec2hosts1
  become: yes
  user: ubuntu
  gather_facts: true
  tasks:
    - pip:
       name: docker-py

- name: Build Jenkins container
  hosts: ec2hosts1
  become: yes
  user: ubuntu
  gather_facts: true
  tasks:
  - name: Start Jenkins container
    docker_container:
      name: jenkins
      image: fjudith/jenkins
      detach: True
      ports:
        - "8080:8080"
        - "50000:50000"
      state: started
      restart_policy: always
  - name: Start Nginx container
    docker_container:
      name: nginx
      image: fjudith/jenkins-nginx
      command: "sleep infinity"
      detach: True
      links:
        - jenkins:jenkins-master
      ports:
        - "80:80"
      state: started
      restart_policy: always

- name: Build Nexus container
  hosts: ec2hosts1
  become: yes
  user: ubuntu
  gather_facts: true
  tasks:
  - name: Start Nexus container
    docker_container:
      name: nexus
      image: sonatype/nexus
      ports:
        - "8081:8081"
      state: started
      restart_policy: always

- name: Build Tomcat container
  hosts: ec2hosts1
  become: yes
  user: ubuntu
  gather_facts: true
  tasks:
  - name: Start Tomcat container
    docker_container:
      name: tomcat
      image: cloudesire/tomcat:7-jre8
      ports:
        - "8888:8080"
      state: started
      restart_policy: always
      env:
        TOMCAT_PASS: thispass
