---

- name: Wait for SSH to come up
  become: yes
  wait_for:
  host: 35.177.226.33 
  port: 22
  delay: 20
  timeout: 500

- name: configuration play
  hosts: ec2hosts
  become: yes
  user: ubuntu
  gather_facts: true
  tasks:
    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes
      with_items:
        - git
        - docker.io

- name: Build an image by running ansible in a container
  hosts: ec2hosts
  become: yes
  tasks:
  - name: Start a container
    docker_container:
      name: jenkins
      image: jenkins:latest
      command: "sleep infinity"




