---

#- hosts: localhost
#  connection: local
#  gather_facts: False
##  include_vars: setupvariables.yml
#  tasks:
#    - name: Provision a set of instances
#      ec2:
#         aws_access_key: 
#         aws_secret_key: 
#         key_name: Team2KP
#         vpc_subnet_id: subnet-7d578c06
#         group: team2DEV
#         instance_type: t2.micro
#         image: ami-f1d7c395
#         wait: true
#         exact_count: 1
#         region: eu-west-2
#         user_data: "{{ lookup('file', 'remove.sh') }}"
#         count_tag:
#            Name: Team2Agent3
#         instance_tags:
#            Name: Team2Agent3
#      register: ec2

#    - name: Add all instance public IPs to host group
#      become: yes
#      add_host: hostname={{ item.public_ip }} groups=ec2hosts3
#      with_items: "{{ ec2.instances }}"

#    - name: Wait for SSH to come up
#      become: yes
#      wait_for:
#        host: "{{ item.public_dns_name }}"
#        port: 22
#        delay: 20
#        timeout: 500
#        state: started
#      with_items: "{{ ec2.instances }}"

#- name: dependency provisioning
#  hosts: all
#  become: yes
#  become_method: sudo
#  gather_facts: false
#  tasks:
#    - name: install python2
#      raw: sudo apt-get -y install python-simplejson


- name: install zabbix
  hosts: ec2hosts3
  remote_user: ubuntu
  become: yes
  tasks:
   - name: update package manager
     apt: update_cache=yes

   - name: Install mysql
     docker_container:
       name: mysqlzab
       image: mysql:mysql
       state: started
       env:
         MYSQL_ROOT_PASSWORD: zabb
         MYSQL_USER: zabbix
         MYSQL_PASSWORD: zabbix

   - name: Install zabbix server
     docker_container:
       name: zabbixserver
       image: zabbix/zabbix-server-mysql
       state: started
       links: "mysqlmzab"
       env:
        DB_SERVER_HOST: mysqlzab
        MYSQL_USER: zabbix
        MYSQL_PASSWORD: password

   - name: Install zabbix frontend on Ubuntu
     docker_container:
       name: zabbixapache
       image: zabbix/zabbix-web-apache-mysql:ubuntu-3.0-latest
       state: started
       restart: yes
       links:
        - "mysqlzab:mzab"
        - "zabbixserver:zserver"
       env:
        DB_SERVER_HOST: mysqlzab
        MYSQL_USER: zabbix
        MYSQL_PASSWORD: password
        PHP_TZ: Europe/London
        ZBX_SERVER_HOST: zabbixserver
